### ISSUE TITLE
API version retirements

### ISSUE THREAD

**Issue by joelbudu** [microsoft/azure-api-management-monetization#58]
Hi,
It seems like the Azure Javascript SDK version (7.0.0) being used in this app for ARM API management has been retired.
[https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023?WT.mc_id=Portal-Microsoft_Azure_Expert](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023?WT.mc_id=Portal-Microsoft_Azure_Expert)

I'm getting errors that look like this:
```
2023-10-23T23:41:17.533579576Z: [ERROR]  (node:1) UnhandledPromiseRejectionWarning: Error: Failed to connect to Management endpoint Port 3443 at endpoint <app_name>.management.azure-api.net for the service.
2023-10-23T23:41:17.533596418Z: [ERROR]      at new RestError (/usr/app/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2469:28)
2023-10-23T23:41:17.533614762Z: [ERROR]      at /usr/app/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3671:37
2023-10-23T23:41:17.533621214Z: [ERROR]      at runMicrotasks (<anonymous>)
2023-10-23T23:41:17.533625974Z: [ERROR]      at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-10-23T23:41:17.533630712Z: [ERROR]  (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 455236)
```
which causes an infinite loop every midnight when attempting to report Stripe billing.

Any assistance would be greatly appreciated.

**Comment by joelbudu** [comment]
Seems like this wasn't the issue. Created the actual one here #59
